"""add team-player ondelete cascade

Revision ID: cf7cb93a17d5
Revises: 873878f1e31f
Create Date: 2025-12-28 23:36:31.093999+00:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf7cb93a17d5'
down_revision: Union[str, Sequence[str], None] = '873878f1e31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('team_player_team_id_fkey'),
        'team_player',
        type_='foreignkey')
    op.create_foreign_key(
        None,
        'team_player',
        'team',
        ['team_id'],
        ['id'],
        ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('team_player_team_id_fkey'),
        'team_player',
        type_='foreignkey')
    op.create_foreign_key(
        op.f('team_player_team_id_fkey'),
        'team_player',
        'team',
        ['team_id'],
        ['id'])
    # ### end Alembic commands ###
