"""Add sets and player tables

Revision ID: 743a82a99bd9
Revises: 53545f86378f
Create Date: 2025-12-04 12:11:59.129037+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '743a82a99bd9'
down_revision: Union[str, Sequence[str], None] = '53545f86378f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamer_tag', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_seed', sa.Integer(), nullable=False),
    sa.Column('loser_seed', sa.Integer(), nullable=False),
    sa.Column('winner_score', sa.Integer(), nullable=False),
    sa.Column('loser_score', sa.Integer(), nullable=False),
    sa.Column('winner_player_id', sa.Integer(), nullable=False),
    sa.Column('loser_player_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['loser_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winner_player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_event_id'), 'set', ['event_id'], unique=False)
    op.create_index(op.f('ix_set_id'), 'set', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_id'), table_name='set')
    op.drop_index(op.f('ix_set_event_id'), table_name='set')
    op.drop_table('set')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
