"""Remove eventdb slug and state mapping

Revision ID: 1184ed4b69c2
Revises: 53545f86378f
Create Date: 2025-12-03 21:51:12.070570+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1184ed4b69c2'
down_revision: Union[str, Sequence[str], None] = '53545f86378f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'state')
    op.drop_column('event', 'slug')
    sa.Enum(
        'CREATED',
        'ACTIVE',
        'COMPLETED',
        'READY',
        'INVALID',
        'CALLED',
        'QUEUED',
        name='activitystate'
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False))

    activity_state_enum = postgresql.ENUM(
        'CREATED',
        'ACTIVE',
        'COMPLETED',
        'READY',
        'INVALID',
        'CALLED',
        'QUEUED',
        name='activitystate'
    )
    activity_state_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'event',
        sa.Column(
            'state',
            activity_state_enum,
            autoincrement=False,
            nullable=False
        )
    )
    # ### end Alembic commands ###
