"""add delete on cascade

Revision ID: 53eb75b221e1
Revises: 1d670ab30ba2
Create Date: 2025-12-25 12:22:08.700803+00:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53eb75b221e1'
down_revision: Union[str, Sequence[str], None] = '1d670ab30ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('event_tournament_id_fkey'),
        'event',
        type_='foreignkey')
    op.create_foreign_key(
        op.f('event_tournament_id_fkey'),
        'event',
        'tournament',
        ['tournament_id'],
        ['id'],
        ondelete='CASCADE')

    op.drop_constraint(op.f('set_event_id_fkey'), 'set', type_='foreignkey')
    op.create_foreign_key(
        op.f('set_event_id_fkey'),
        'set',
        'event',
        ['event_id'],
        ['id'],
        ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('set_event_id_fkey'), 'set', type_='foreignkey')
    op.create_foreign_key(
        op.f('set_event_id_fkey'),
        'set',
        'event',
        ['event_id'],
        ['id'])

    op.drop_constraint(
        op.f('event_tournament_id_fkey'),
        'event',
        type_='foreignkey')
    op.create_foreign_key(
        op.f('event_tournament_id_fkey'),
        'event',
        'tournament',
        ['tournament_id'],
        ['id'])
    # ### end Alembic commands ###
