"""tournament city optional

Revision ID: 2b09db28988c
Revises: 743a82a99bd9
Create Date: 2025-12-14 16:26:14.371156+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b09db28988c'
down_revision: Union[str, Sequence[str], None] = '743a82a99bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournament', 'city',
                    existing_type=sa.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournament', 'city',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
